from collections.abc import Callable
from typing import Any

__version__: str

class CoreConfigError(Exception): ...
class CoreFormatError(Exception): ...
class CoreSourceError(Exception): ...

def api_version() -> int: ...
def algo_version() -> int: ...
def default_masks() -> list[dict[str, Any]]: ...
def match_templates(
    kind: str, before: list[str], after: list[str], threshold: float | None = None
) -> list[tuple[int, int]]: ...
def mine(request: dict[str, Any], progress: Callable[[int], None] | None = None) -> dict[str, Any]: ...
